name: Sample next app
on: push
jobs:
    build-project:
        name: Build project
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install node dep
          run: npm install
        - name: Build assets
          run: npm run build